//Problem number 2:

/*Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence
whose values do not exceed four million, find the sum of the even-valued terms.*/

var sum = 2;			// final result 
var pp = 1;				// previous-to-previous term
var p = 2;				// previous term
var c = p + pp;			// current term

for(;c <= 4000000;){
    if(c%2 === 0){
        sum += c;		
    }
    pp = p;
    p = c;
    c = p +pp;
}

console.log(sum);
